= Relaton Render

image:https://img.shields.io/gem/v/iso690render.svg["Gem Version", link="https://rubygems.org/gems/iso690render"]
image:https://github.com/metanorma/iso690render/workflows/rake/badge.svg["Build Status", link="https://github.com/metanorma/iso690render/actions?workflow=rake"]
image:https://codeclimate.com/github/metanorma/iso690render/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/metanorma/iso690render"]

Gem that takes a https://github.com/relaton/relaton[Relaton] bibliographic description and 
a configuration, and generates a https://www.metanorma.org[Metanorma] XML rendering of that description.

[source,ruby]
----
input = "<bibitem type='...'>....</bibitem>"

Iso690Render.new(template: template, lang: "en").render(input)
----

The gem is intended to be inherited from by Metanorma flavours, which may specialise it with their own
code. The templates are however intended to determine much of the rendering.

There is one template provided for each of the bibliographic types recognised by Relaton, and a default template:

* article 
* book 
* booklet 
* manual 
* proceedings 
* presentation 
* thesis 
* techreport 
* standard 
* unpublished 
* map 
* electronic resource 
* audiovisual 
* film 
* video 
* broadcast 
* software 
* graphic_work 
* music 
* patent 
* inbook 
* incollection 
* inproceedings 
* journal 
* website
* webresource
* dataset
* archival 
* social_media 
* alert 
* message 
* conversation 
* misc (default)

In Metanorma, not all types are used, but there are exemplars for all of these given on this site, following
the human-readable style used in ISO 690.

Each `template` is a string marked up with https://shopify.github.io/liquid/[Liquid Markup], with the following fields
drawn from the bibliographic item:

|===
| Field   | Relaton XPath | Multiple | Can come from host | Note

| title   | ./title | | |
| edition | ./edition | | Y |
| medium  | ./medium | | Y |
| place   | ./place | | Y |
| publisher | ./contributor[role/@type = 'publisher']/organization/name | | Y | 
| standardidentifier | ./docidentifier[not(@type = 'metanorma' or @type = 'ordinal')] | Y | |
| status | ./status | | | Rendering varies by flavour
| uri | ./uri[@type = 'doi' or @type = 'uri' or @type = 'src' or true] | | |
| access_location | ./accessLocation | | Y |
| extent | ./extent | Y | | Render with standard abbreviations for pp, vols, with n-dash, with delimiting of multiple locations
| creatornames | ./contributor[role/@type = 'author'] \| ./contributor[role/@type = 'performer'] \| ./contributor[role/@type = 'adapter'] \| ./contributor[role/@type = 'translator'] \| ./contributor[role/@type = 'editor'] \| ./contributor[role/@type = 'publisher'] \| ./contributor[role/@type = 'distributor'] \| ./contributor | Y | | name_template applied to each name; joining template applied to multiple names; contributor role suffixed to sequence of names
| date | ./date[@type = 'issued'] \| ./date[@type = 'circulated'] \| ./date | | Y |
| date_updated | ./date[@type = 'updated'] | | Y | 
| series_title  | ./series[@type = 'main' or not(@type) or true]/name | | Y |
| series_abbr  | ./series[@type = 'main' or not(@type) or true]/abbreviation | | Y |
| series_num  | ./series[@type = 'main' or not(@type) or true]/number | | Y |
| series_partnumber  | ./series[@type = 'main' or not(@type) or true]/partnumber | | Y |
| host_creatornames | ./relation[@type = 'includedIn']/bibitem/contributor[role/@type = 'author'] | |  Y | Follows options for `creatornames`
| host_title | ./relation[@type = 'includedIn']/bibitem/title | Y | Y | Follows options for `creatornames`
| type | ./@type | |
| labels | | | text to be looked up in internationalisation configuration files: "edition", "In", "At", "Vol", "Vols", "p.", "pp" 
|===

Many fields are populated either by the description of the bibliographic item itself, or by the description of the item containing it (the _host_ item: `./relation[@type = 'includedIn']`). For example, in a paper included in an edited volume, the edition will typically be given for the editor volume, rather than for the paper. Those fields are indicated by "Can come from host" in the table.

The Liquid template surrounds each field by preceding and following punctuation, which is meant to be space delimited. 

* If the field is empty, its surrounding markup is also removed. 
* Underscore is treated as space, attaching to the preceding or following field.
* If punctuation is space delimited and preceded by `|`, it is inserted regardless of preceding content.

For example:

....
"{{ creatornames }} ({{date}}) |. <em>{{ title }}</em> [{{medium}}] ,_{{ edition }}_edition |."
....

The `nametemplate` is also a Liquid template for the formatting of contributor names in particular positions. It
draws on the following fields frawn from the bibliographic item:

|===
| Field  | Relaton XPath | Note

| surname | ./contributor[1]/name/surname |
| surname2 | ./contributor[2]/name/surname |
| surname3 | ./contributor[3]/name/surname |
| initials | ./contributor[1]/name/initial |
| initials2 | ./contributor[2]/name/initial |
| given | ./contributor[1]/name/forename[1] |
| given2 |  ./contributor[2]/name/forename[1] |
| middle | ./contributor[1]/name/forename[not(first())] |
| middle2 | ./contributor[2]/name/forename[not(first())] |
| role | ./contributor[1]/role \| ./contributor[1]/role/@type |
| role2 | ./contributor[1]/role \| ./contributor[2]/role/@type |
|===

There are at least three distinct nametemplate instances that need to be provided, one for a single contributor, one for two contributors, one for three or more. If more nametemplate instances are provided, they apply for the matching number of contributors, up to the last template. For example, if five templates are provided, they apply to 1, 2, 3, 4, or 5 or more contributors.

For example:
....
[
  "{{ surname }}, {{ given}} {{middle | slice : 0 }}",
  "{{ surname }}, {{ given}} {{middle | slice : 0 }} &amp; {{ given2 }} {{middle2 | slice : 0 }} {{ surname2 }}",
  "{{ surname }}, {{ given}} {{middle | slice : 0 }}, {{ given2 }} {{middle2 | slice : 0 }} {{ surname2 }} &amp; {{ given3 }} {{middle3 | slice : 0 }} {{ surname3 }}",
  "{{ surname }}, {{ given}} {{middle | slice : 0 }}, {{ given2 }} {{middle2 | slice : 0 }} {{ surname2 }}, {{ given3 }} {{middle3 | slice : 0 }} {{ surname3 }} &amp; {{ given4 }} {{middle4 | slice : 0 }} {{ surname4 }}",
  "{{ surname }}, {{ given}} {{middle | slice : 0 }}, {{ given2 }} {{middle2 | slice : 0 }} {{ surname2 }} <em>et al.</em>"
]
....


In addition, the stylesheet includes different configuration options for rendering:

