= Relaton Render

image:https://img.shields.io/gem/v/iso690render.svg["Gem Version", link="https://rubygems.org/gems/iso690render"]
image:https://github.com/metanorma/iso690render/workflows/rake/badge.svg["Build Status", link="https://github.com/metanorma/iso690render/actions?workflow=rake"]
image:https://codeclimate.com/github/metanorma/iso690render/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/metanorma/iso690render"]

Gem that takes a https://github.com/relaton/relaton[Relaton] bibliographic description and 
a configuration, and generates a https://www.metanorma.org[Metanorma] XML rendering of that description.

== Calling

[source,ruby]
----
input = "<bibitem type='...'>....</bibitem>"

Iso690Render.new(template: ..., nametemplate: ..., seriestemplate: ..., language: "en", script: "Latn").render(input)
----

The gem is intended to be inherited from by Metanorma flavours, which may specialise it with their own
code. The templates are however intended to determine much of the rendering.

Gems can provide their configurations in YAML files, and parse them before passing them to the call to Iso690Render.
The built-in values for Iso690Render are given in `/lib/iso690render/config.yml`, and can be overridden by
the parameters of initialising Iso690Render.

The parameters are:

`language`:: in ISO-639
`script`:: in ISO-15124
`template`:: templates for rendering different bibliographic types
`nametemplate`:: templates for rendering personal names
`seriestemplate`:: templates for rendering series

== Configuration

=== Templates

There is one template provided for each of the bibliographic types recognised by Relaton, and a default template:

* article 
* book 
* booklet 
* manual 
* proceedings 
* presentation 
* thesis 
* techreport 
* standard 
* unpublished 
* map 
* electronic resource 
* audiovisual 
* film 
* video 
* broadcast 
* software 
* graphic_work 
* music 
* patent 
* inbook 
* incollection 
* inproceedings 
* journal 
* website
* webresource
* dataset
* archival 
* social_media 
* alert 
* message 
* conversation 
* misc (default)

In Metanorma, not all types are used, but there are exemplars for all of these given on this site, following
the human-readable style used in ISO 690. These can be overridden by supplying corresponding paramerers in the call
to initialise Iso690Render.

Each `template` is a string marked up with https://shopify.github.io/liquid/[Liquid Markup], with the following fields
drawn from the bibliographic item:

|===
| Field   | Relaton XPath | Multiple | Can come from host | Note

| title   | ./title | | |
| edition | ./edition | | Y |
| medium  | ./medium | | Y |
| place   | ./place | | Y |
| publisher | ./contributor[role/@type = 'publisher']/organization/name | | Y | 
| standardidentifier | ./docidentifier[not(@type = 'metanorma' or @type = 'ordinal')] | Y | |
| status | ./status | | | Rendering varies by flavour
| uri | ./uri[@type = 'doi' or @type = 'uri' or @type = 'src' or true] | | |
| access_location | ./accessLocation | | Y |
| extent | ./extent | Y | | Render with standard abbreviations for pp, vols, with n-dash, with delimiting of multiple locations
| creatornames | ./contributor[role/@type = 'author'] \| ./contributor[role/@type = 'performer'] \| ./contributor[role/@type = 'adapter'] \| ./contributor[role/@type = 'translator'] \| ./contributor[role/@type = 'editor'] \| ./contributor[role/@type = 'publisher'] \| ./contributor[role/@type = 'distributor'] \| ./contributor | Y | | <<nametemplate,`nametemplate`>> applied to each name; joining template from internationalisation applied to multiple names
| role | ./contributor[role/description] \| ./contributor[role/@type] | | | 
| date | ./date[@type = 'issued'] \| ./date[@type = 'circulated'] \| ./date | | Y |
| date_updated | ./date[@type = 'updated'] | | Y | 
| date_accessed | ./date[@type = 'accessed'] | | Y | 
| series | ./series[@type = 'main' or not(@type) or true] | | Y | <<seriestemplate,`seriestemplate`>> applies to series
| host_creatornames | ./relation[@type = 'includedIn']/bibitem/contributor[role/@type = 'author'] | |  Y | Follows options for `creatornames`
| host_title | ./relation[@type = 'includedIn']/bibitem/title | Y | Y | Follows options for `creatornames`
| host_role | ./relation[@type = 'includedIn']/bibitem/contributor[role/description] \| ./relation[@type = 'includedIn']/bibitem/contributor[role/@type] | | Y | 
| type | ./@type | |
| labels | | | text to be looked up in internationalisation configuration files: "edition", "In", "At", "Vol", "Vols", "p.", "pp" 
|===

Many fields are populated either by the description of the bibliographic item itself, or by the description of the item containing it (the _host_ item: `./relation[@type = 'includedIn']/bibitem`). For example, in a paper included in an edited volume, the edition will typically be given for the editor volume, rather than for the paper. Those fields are indicated by "Can come from host" in the table.

The Liquid template surrounds each field by preceding and following punctuation, which is meant to be space delimited. 

* If the field is empty, its surrounding markup is also removed. 
* Underscore is treated as space, attaching to the preceding or following field.
* If punctuation is space delimited and preceded by `|`, it is inserted regardless of preceding content.

For example:

....
"{{ creatornames }} ({{date}}) |. <em>{{ title }}</em> [{{medium}}] ,_{{ edition }}_{{ labels['edition'] }} |."
....

[[nametemplate]]
=== Name templates

The `nametemplate` is a hash of Liquid templates for the formatting of contributor names in particular positions. It
draws on the following fields drawn from the bibliographic item:

|===
| Field  | Relaton XPath | Multiple | Note

| surname[0] | ./contributor[1]/person/name/surname \| ./contributor[1]/person/name/completename \| ./contributor[1]/organization/name | | i.e. surname is the name default
| surname[1] | ./contributor[2]/name/surname | |
| surname[2] | ./contributor[3]/name/surname | |
| initials[0] | ./contributor[1]/name/initial | |
| initials[1] | ./contributor[2]/name/initial | |
| given[0] | ./contributor[1]/name/forename[1] | |
| given[1] |  ./contributor[2]/name/forename[1] | |
| middle[0] | ./contributor[1]/name/forename[not(first())] | Y |
| middle[1] | ./contributor[2]/name/forename[not(first())] | Y |
|===

There are at least three distinct `nametemplate` instances that need to be provided, one for a single contributor (`one:`), one for two contributors (`two:`), one for three or more (`more:`), and optionally one for "et al." (`etal:`). The number of contributors for which "et al." starts being used is indicated by `etal_count`.

For example:
....
{
  one: "{{ surname[0] }}, {{ given[0] }} {{ middle[0] | slice : 0 }}",
  two: "{{ surname[0] }}, {{ given[0] }} {{ middle[0] | slice : 0 }} &amp; {{ given[1] }} {{ middle[1] | slice : 0 }} {{ surname[1] }}",
  more: "{{ surname[0] }}, {{ given[0] }} {{ middle[0] | slice : 0 }}, {{ given[1] }} {{ middle[1] | slice : 0 }} {{ surname[1] }} &amp; {{ given[2] }} {{ middle[2] | slice : 0 }} {{ surname[2] }}",
  etal: "{{ surname[0] }}, {{ given[0] }} {{ middle[0] | slice : 0 }}, {{ given[1] }} {{ middle[1] | slice : 0 }} {{ surname[1] }} <em>et al.</em>",
  etal_count: 6
}
....

In the case of `more`, the `(name)[1]` entries are repeated for all additional authors above 2 and before the final author.

[[seriestemplate]]
=== Series template

The `seriestemplate` is a template for the rendering of series information. It draws on the following fields drawn from the bibliographic item:

|===
| Field  | Relaton XPath | Multiple | Can come from host | Note

| series_title  | ./series[@type = 'main' or not(@type) or true]/name | | Y |
| series_abbr  | ./series[@type = 'main' or not(@type) or true]/abbreviation | | Y |
| series_num  | ./series[@type = 'main' or not(@type) or true]/number | | Y |
| series_partnumber  | ./series[@type = 'main' or not(@type) or true]/partnumber | | Y |
|===

=== Other

In addition, the stylesheet includes different configuration options for rendering:


